name = "lucky"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "lucky-production"
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "./"
watch_paths = []

[build.upload]
format = "modules"
main = "./dist"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt"]
fallthrough = true

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true
